image: node:6

#Job for Linting and Testing
linting_and_testing:
  script:
    #Navigate to frontend folder, with package.json and .eslintrc.yml
    - cd ./Projekt/src/frontend
    #Installing all dependencies from package.json
    #- npm install
    - npm install eslint
        -npm install eslint-config-standard
            -npm install eslint-plugin-import
            -npm install eslint-plugin-node
            -npm install eslint-plugin-promise
            -npm install eslint-plugin-standard
        - npm install eslint-plugin-vue
    - npm run lint
    #- npm run unit
    
    #Alternatively run linting from locally installed eslint, for all .js files in current folder (frontend)
    #- ./node_modules/.bin/eslint .

