image: node:6

stages:
  - lint

eslint:
  stage: lint
  script:
    # Install ESLint in this docker container
    
    - npm install eslint
    - npm install eslint-plugin-vue
    - npm install eslint-config-standard
    # Run ESLint
    - ./node_modules/.bin/eslint .