image: node:6

stages:
  - lint

eslint:
  stage: lint
  script:
    - nodejs --version
    # Install ESLint in this docker container
    - npm install -g ajv
    - npm install -g eslint
    # Configure ESLint (will read your .eslintrc file)
    # - eslint --init
    # Run ESLint
    - eslint *.js