image: node:6

jslinting:
  script:
    #Navigate to frontend folder, with package.json and .eslintrc.yml
    - cd ./Projekt/src/frontend
    
    # Installing eslint and dependencies
    - npm install eslint eslint-config-standard eslint-plugin-import eslint-plugin-node eslint-plugin-promise eslint-plugin-standard eslint-plugin-vue babel-eslint
    - npm run lint
    
    # Installing jest, vue-test-utils and dependencies
    - npm install jest jest-serializer-vue vue-jest vue-template-compiler babel-jest vue @vue/test-utils babel-preset-stage-2 babel-plugin-dynamic-import-node vuex
    - npm run unit
    
validate_time_tracking:
  image:
    name: mribeiro/xmllint
    entrypoint: [""]
  script:
    - xmllint --version
    - sh validate-xml.sh
  
