stages:
  - xmlinting
  - pythontesting
  - jslinting_and_testing
  

validate_time_tracking:
  stage: xmlinting
  image:
    name: mribeiro/xmllint
    entrypoint: [""]
  script:
    - xmllint --version
    - sh validate-xml.sh
  only:
    - master

pythontesting:
  stage: pythontesting
  image:
    name: python:2.7
  script:
    - cd ./Projekt/src/print_service
    - python print_service.test.py -v

jslinting_and_testing:
  stage: jslinting_and_testing
  image: 
    name: node:6
  script:
    #Navigate to frontend folder, with package.json and .eslintrc.yml
    - cd ./Projekt/src/frontend
    
    # Installing eslint and dependencies
    - npm install eslint eslint-config-standard eslint-plugin-import eslint-plugin-node eslint-plugin-promise eslint-plugin-standard eslint-plugin-vue babel-eslint
    - npm run lint
    
    # Installing jest, vue-test-utils and dependencies
    - npm install jest jest-serializer-vue vue-jest vue-template-compiler babel-jest vue @vue/test-utils babel-preset-stage-2 babel-plugin-dynamic-import-node vuex axios element-ui vue-server-renderer
    - npm run unit
    
