image: node:6

#Job for Linting and Testing
linting_and_testing:
  script:
    #Navigate to frontend folder, with package.json and .eslintrc.yml
    - cd ./Projekt/src/frontend
    #Installing all dependencies from package.json
    #- npm install
    - npm install eslint
        -npm install eslint-config-standard
            -npm install eslint-plugin-import
            -npm install eslint-plugin-node
            -npm install eslint-plugin-promise
            -npm install eslint-plugin-standard
    - npm run lint
    #- npm run unit
    
    #Alternatively run linting from locally installed eslint, for all .js files in current folder (frontend)
    #- ./node_modules/.bin/eslint .

validate_time_tracking:
  image:
    name: mribeiro/xmllint
    entrypoint: [""]
  script:
    - xmllint --version
    - sh validate-xml.sh

release-job:
  before_script:
    - npm install -g markdown-pdf
  script:
    - sh program.sh
    - markdown-pdf result.md
    - markdown-pdf Webseiten/docu.md
    - mv Webseiten/docu.pdf docu.pdf
  artifacts:
    paths:
    - result.pdf
    - docu.pdf
  only:
    - tags

