all:
	pdflatex entwurfsbeschreibung; makeglossaries entwurfsbeschreibung; pdflatex entwurfsbeschreibung; pdflatex entwurfsbeschreibung

clean:
	rm entwurfsbeschreibung.aux
	rm entwurfsbeschreibung.glg
	rm entwurfsbeschreibung.glo
	rm entwurfsbeschreibung.gls
	rm entwurfsbeschreibung.glsdefs
	rm entwurfsbeschreibung.ist
	rm entwurfsbeschreibung.log
	rm entwurfsbeschreibung.out
	rm entwurfsbeschreibung.toc
